name: Run Projekt Gruppuppgift

on: # Trigger events
  push: # Trigger on push to branches
    branches:
      - main
  pull_request: # Trigger on pull requests to branches
    branches:
      - main



jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Debug

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/grupp2-assigmnet-ci-cd

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/grupp2-assigmnet-ci-cd:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/grupp2-assigmnet-ci-cd:latest